tests/kern/tfcntl2: drop dead code
Problem: gcc9 emits warning about unused sf_unlock struct.

tfcntl2.c:39:27: error: ‘sf_unlock’ defined but not used [-Werror=unused-const-variable=]
   39 | static const struct flock sf_unlock = {
      |                           ^~~~~~~~~

It is indeed not used, so drop it.