tests/kern/fsx: ignore unused-result warnings
Problem: gcc9 emits unused-result errors on ftruncate.

fsx.c: In function ‘check_trunc_hack’:
fsx.c:474:2: error: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Werror=unused-result]
  474 |  ftruncate(fd, (off_t)0);
      |  ^~~~~~~~~~~~~~~~~~~~~~~
fsx.c:475:2: error: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Werror=unused-result]
  475 |  ftruncate(fd, (off_t)100000);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
fsx.c:481:2: error: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Werror=unused-result]
  481 |  ftruncate(fd, 0);
      |  ^~~~~~~~~~~~~~~~
fsx.c: In function ‘test_punch_hole’:
fsx.c:1331:4: error: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Werror=unused-result]
 1331 |    ftruncate(fd, 0);
      |    ^~~~~~~~~~~~~~~~

Not our code, so disable the warning.