testsuite: make unit tests work w/parallel harness
Problem: the test_threadwrlock.t unit test does not work with the
automake parallel test harness, with failures like this:

 PASS: test_threadwrlock.t 1 - proc0 fcntl F_WRLCK 0-63 works
 PASS: test_threadwrlock.t 2 - proc0: F_WRLCK 32-63 works
 PASS: test_threadwrlock.t 3 - proc1: fcntl F_WRLCK 0-63 works
 PASS: test_threadwrlock.t 4 - proc2: fcntl F_WRLCK 0-63 works
 ERROR: test_threadwrlock.t 1 - proc0 fcntl F_WRLCK 0-63 works # OUT-OF-ORDER (expecting 5)
 ERROR: test_threadwrlock.t 2 - proc0: F_WRLCK 32-63 works # OUT-OF-ORDER (expecting 6)
 ERROR: test_threadwrlock.t 3 - proc1: fcntl F_WRLCK 0-63 works # OUT-OF-ORDER (expecting 7)
 ERROR: test_threadwrlock.t 4 - proc2: fcntl F_WRLCK 0-63 works # OUT-OF-ORDER (expecting 8)
 ERROR: test_threadwrlock.t 5 - child0 failed to lock bytes 32-63 as expected # OUT-OF-ORDER (expecting 9)
 ERROR: test_threadwrlock.t 1 - proc0 fcntl F_WRLCK 0-63 works # OUT-OF-ORDER (expecting 10)
 ERROR: test_threadwrlock.t 2 - proc0: F_WRLCK 32-63 works # OUT-OF-ORDER (expecting 11)
 ERROR: test_threadwrlock.t 3 - proc1: fcntl F_WRLCK 0-63 works # OUT-OF-ORDER (expecting 12)
 ERROR: test_threadwrlock.t 4 - proc2: fcntl F_WRLCK 0-63 works # OUT-OF-ORDER (expecting 13)
 ERROR: test_threadwrlock.t 5 - child0 failed to lock bytes 32-63 as expected # OUT-OF-ORDER (expecting 14)
 ERROR: test_threadwrlock.t 6 - child1 failed to lock bytes 32-63 as expected # OUT-OF-ORDER (expecting 15)
 ERROR: test_threadwrlock.t - too many tests run (expected 6, got 15)

Avoid calling exit() from test process children.  Use _exit() instead.

Add a missing done_testing() call here and in one other test, which also
seems to cause problems.