tests/kern/postmark: ignore format-overflow warn
Problem: gcc9 complains of format-overflow problems with sprintf().

postmark.c: In function ‘create_subdirectories.part.0’:
postmark.c:939:52: error: ‘%d’ directive output may be truncated writing between 1 and 10 bytes into a region of size between 0 and 255 [-Werror=format-truncation=]
  939 |          snprintf(dir_name, sizeof (dir_name), "%ss%d",save_dir,i);
      |                                                    ^~
postmark.c:939:48: note: directive argument in the range [0, 2147483646]
  939 |          snprintf(dir_name, sizeof (dir_name), "%ss%d",save_dir,i);
      |                                                ^~~~~~~
postmark.c:939:10: note: ‘snprintf’ output between 3 and 267 bytes into a destination of size 256
  939 |          snprintf(dir_name, sizeof (dir_name), "%ss%d",save_dir,i);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
postmark.c: In function ‘delete_subdirectories.part.0’:
postmark.c:968:31: error: ‘%d’ directive writing between 1 and 10 bytes into a region of size between 0 and 255 [-Werror=format-overflow=]
  968 |          sprintf(dir_name,"%ss%d",save_dir,i);
      |                               ^~
postmark.c:968:27: note: directive argument in the range [0, 2147483646]
  968 |          sprintf(dir_name,"%ss%d",save_dir,i);
      |                           ^~~~~~~
postmark.c:968:10: note: ‘sprintf’ output between 3 and 267 bytes into a destination of size 256
  968 |          sprintf(dir_name,"%ss%d",save_dir,i);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Since this is not our code, just disable the warnings.